// Danh sách ngân hàng đang hoạt động tại Việt Nam (NHTM trong nước, NH 100% vốn nước ngoài,
// NH liên doanh, NH chính sách / hợp tác xã). Dùng cho dropdown "Ngân hàng" ở DNTT.
// `short` = tên ngắn/thương hiệu (giá trị lưu DB), `full` = tên đầy đủ (hiển thị cho rõ).
// Không phụ thuộc nguồn ngoài — cập nhật tay khi danh sách NHNN thay đổi.

export type VnBank = { short: string; full: string };

export const VN_BANKS: VnBank[] = [
  { short: 'Vietcombank', full: 'NH TMCP Ngoại thương Việt Nam (Vietcombank)' },
  { short: 'VietinBank', full: 'NH TMCP Công thương Việt Nam (VietinBank)' },
  { short: 'BIDV', full: 'NH TMCP Đầu tư và Phát triển Việt Nam (BIDV)' },
  { short: 'Agribank', full: 'NH Nông nghiệp và Phát triển Nông thôn Việt Nam (Agribank)' },
  { short: 'Techcombank', full: 'NH TMCP Kỹ thương Việt Nam (Techcombank)' },
  { short: 'MB', full: 'NH TMCP Quân đội (MB Bank)' },
  { short: 'ACB', full: 'NH TMCP Á Châu (ACB)' },
  { short: 'VPBank', full: 'NH TMCP Việt Nam Thịnh Vượng (VPBank)' },
  { short: 'Sacombank', full: 'NH TMCP Sài Gòn Thương Tín (Sacombank)' },
  { short: 'HDBank', full: 'NH TMCP Phát triển TP.HCM (HDBank)' },
  { short: 'VIB', full: 'NH TMCP Quốc tế Việt Nam (VIB)' },
  { short: 'SHB', full: 'NH TMCP Sài Gòn – Hà Nội (SHB)' },
  { short: 'TPBank', full: 'NH TMCP Tiên Phong (TPBank)' },
  { short: 'MSB', full: 'NH TMCP Hàng Hải Việt Nam (MSB)' },
  { short: 'OCB', full: 'NH TMCP Phương Đông (OCB)' },
  { short: 'SeABank', full: 'NH TMCP Đông Nam Á (SeABank)' },
  { short: 'Eximbank', full: 'NH TMCP Xuất Nhập khẩu Việt Nam (Eximbank)' },
  { short: 'LPBank', full: 'NH TMCP Lộc Phát Việt Nam (LPBank)' },
  { short: 'SCB', full: 'NH TMCP Sài Gòn (SCB)' },
  { short: 'ABBANK', full: 'NH TMCP An Bình (ABBANK)' },
  { short: 'Nam A Bank', full: 'NH TMCP Nam Á (Nam A Bank)' },
  { short: 'PVcomBank', full: 'NH TMCP Đại Chúng Việt Nam (PVcomBank)' },
  { short: 'Bac A Bank', full: 'NH TMCP Bắc Á (Bac A Bank)' },
  { short: 'VietABank', full: 'NH TMCP Việt Á (VietABank)' },
  { short: 'NCB', full: 'NH TMCP Quốc Dân (NCB)' },
  { short: 'BVBank', full: 'NH TMCP Bản Việt (BVBank)' },
  { short: 'KienlongBank', full: 'NH TMCP Kiên Long (KienlongBank)' },
  { short: 'Saigonbank', full: 'NH TMCP Sài Gòn Công Thương (Saigonbank)' },
  { short: 'VietBank', full: 'NH TMCP Việt Nam Thương Tín (VietBank)' },
  { short: 'PGBank', full: 'NH TMCP Thịnh vượng và Phát triển (PGBank)' },
  { short: 'BaoViet Bank', full: 'NH TMCP Bảo Việt (BaoViet Bank)' },
  { short: 'DongA Bank', full: 'NH TMCP Đông Á (DongA Bank)' },
  { short: 'OceanBank', full: 'NH TM TNHH MTV Đại Dương (OceanBank)' },
  { short: 'GPBank', full: 'NH TM TNHH MTV Dầu khí Toàn cầu (GPBank)' },
  { short: 'CBBank', full: 'NH TM TNHH MTV Xây dựng Việt Nam (CBBank)' },
  { short: 'Public Bank', full: 'NH TNHH MTV Public Việt Nam (PBVN)' },
  { short: 'Shinhan Bank', full: 'NH TNHH MTV Shinhan Việt Nam (Shinhan Bank)' },
  { short: 'HSBC', full: 'NH TNHH MTV HSBC Việt Nam (HSBC)' },
  { short: 'Standard Chartered', full: 'NH TNHH MTV Standard Chartered Việt Nam' },
  { short: 'Woori Bank', full: 'NH TNHH MTV Woori Việt Nam (Woori Bank)' },
  { short: 'UOB', full: 'NH TNHH MTV UOB Việt Nam (UOB)' },
  { short: 'CIMB', full: 'NH TNHH MTV CIMB Việt Nam (CIMB)' },
  { short: 'Hong Leong Bank', full: 'NH TNHH MTV Hong Leong Việt Nam' },
  { short: 'IBK', full: 'NH Công nghiệp Hàn Quốc (IBK)' },
  { short: 'Citibank', full: 'NH Citibank, N.A. – CN Việt Nam (Citibank)' },
  { short: 'Co-opBank', full: 'NH Hợp tác xã Việt Nam (Co-opBank)' },
  { short: 'VRB', full: 'NH Liên doanh Việt – Nga (VRB)' },
  { short: 'Indovina Bank', full: 'NH TNHH Indovina (IVB)' },
  { short: 'VBSP', full: 'NH Chính sách xã hội Việt Nam (VBSP)' },
];
