-- ============================================================
-- AVPG KSNB — schema Postgres (self-hosted).
-- Gộp trạng thái cuối của migrations D1 0001..0006 + ephemeral_kv.
-- Timestamps lưu dạng text ISO8601 UTC (giống D1) → iso_now() sinh đúng format
-- khớp nowIso() ở app layer, tránh lệch kiểu khi adapter dịch datetime('now').
-- ============================================================

-- Hàm sinh timestamp ISO khớp Date.toISOString(): 2026-05-25T09:00:00.123Z
CREATE OR REPLACE FUNCTION iso_now() RETURNS text
  LANGUAGE sql STABLE AS $$
  SELECT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')
$$;

-- 1. departments
CREATE TABLE departments (
  code        text PRIMARY KEY,
  ad_name     text NOT NULL UNIQUE,
  full_name   text NOT NULL,
  is_active   integer NOT NULL DEFAULT 1,
  created_at  text NOT NULL DEFAULT iso_now(),
  updated_at  text NOT NULL DEFAULT iso_now()
);

-- 2. department_managers
CREATE TABLE department_managers (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dept_code   text NOT NULL REFERENCES departments(code),
  user_email  text NOT NULL,
  user_name   text NOT NULL,
  is_active   integer NOT NULL DEFAULT 1,
  created_at  text NOT NULL DEFAULT iso_now()
);
CREATE INDEX idx_dept_managers_dept ON department_managers(dept_code, is_active);

-- 3. bod_members
CREATE TABLE bod_members (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_email    text NOT NULL UNIQUE,
  user_name     text NOT NULL,
  routing_order integer NOT NULL DEFAULT 1,
  is_active     integer NOT NULL DEFAULT 1,
  created_at    text NOT NULL DEFAULT iso_now()
);

-- 4. users (gồm signature_data_url [0003], account_enabled/account_checked_at [0006])
CREATE TABLE users (
  id                 text PRIMARY KEY,
  email              text NOT NULL UNIQUE,
  display_name       text NOT NULL,
  job_title          text,
  ad_department      text,
  dept_code          text REFERENCES departments(code),
  telegram_chat_id   text UNIQUE,
  last_seen_at       text NOT NULL DEFAULT iso_now(),
  created_at         text NOT NULL DEFAULT iso_now(),
  signature_data_url text,
  account_enabled    integer NOT NULL DEFAULT 1,
  account_checked_at text
);
CREATE INDEX idx_users_dept ON users(dept_code);

-- 5. proposal_counters (atomic mã phiếu)
CREATE TABLE proposal_counters (
  dept_code text NOT NULL,
  date_key  text NOT NULL,
  counter   integer NOT NULL DEFAULT 0,
  PRIMARY KEY (dept_code, date_key)
);

-- 6. proposals (trạng thái cuối sau 0005 — gồm cột PR)
CREATE TABLE proposals (
  id                integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code              text UNIQUE,
  proposal_type     text NOT NULL DEFAULT 'general'
                       CHECK (proposal_type IN ('general','purchase')),
  status            text NOT NULL DEFAULT 'draft'
                       CHECK (status IN (
                         'draft','submitted','manager_approved',
                         'en_approved','ic_approved',
                         'bod_approved','completed','rejected','cancelled'
                       )),
  proposer_user_id  text NOT NULL REFERENCES users(id),
  proposer_name     text NOT NULL,
  proposer_title    text,
  proposer_dept     text NOT NULL REFERENCES departments(code),

  title             text NOT NULL,
  reason            text NOT NULL,
  explanation       text,
  required_time     text,

  manager_email     text,
  manager_name      text,
  bod_email         text,
  bod_name          text,

  engineering_required integer NOT NULL DEFAULT 0,
  engineering_email    text,
  engineering_name     text,
  engineering_acted_at text,
  ic_email             text,
  ic_name              text,
  ic_acted_at          text,

  delivery_date        text,
  suggested_vendor_1   text,
  suggested_vendor_2   text,
  suggested_vendor_3   text,
  subtotal             bigint,   -- VND (bigint vì có thể > 2.1 tỷ)
  vat_amount           bigint,
  total_amount         bigint,

  rejected_reason   text,
  created_at        text NOT NULL DEFAULT iso_now(),
  submitted_at      text,
  manager_acted_at  text,
  bod_acted_at      text,
  completed_at      text,
  updated_at        text NOT NULL DEFAULT iso_now()
);
CREATE INDEX idx_proposals_status        ON proposals(status);
CREATE INDEX idx_proposals_proposer      ON proposals(proposer_user_id, status);
CREATE INDEX idx_proposals_manager_inbox ON proposals(manager_email, status);
CREATE INDEX idx_proposals_bod_inbox     ON proposals(bod_email, status);
CREATE INDEX idx_proposals_en_inbox      ON proposals(engineering_email, status);
CREATE INDEX idx_proposals_ic_inbox      ON proposals(ic_email, status);
CREATE INDEX idx_proposals_code          ON proposals(code);
CREATE INDEX idx_proposals_type          ON proposals(proposal_type, status);

-- 7. proposal_items (gồm cột PR [0005])
CREATE TABLE proposal_items (
  id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  proposal_id  integer NOT NULL REFERENCES proposals(id) ON DELETE CASCADE,
  seq          integer NOT NULL,
  content      text NOT NULL,
  note         text,
  item_name    text,
  spec         text,
  unit         text,
  qty_stock    integer,
  qty_buy      integer,
  unit_price   bigint,
  line_total   bigint,
  purpose      text
);
CREATE UNIQUE INDEX idx_items_proposal_seq ON proposal_items(proposal_id, seq);

-- 8. approvals (step gồm engineering/ic [0005])
CREATE TABLE approvals (
  id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  proposal_id  integer NOT NULL REFERENCES proposals(id) ON DELETE CASCADE,
  step         text NOT NULL CHECK (step IN ('manager','bod','ksnb','engineering','ic')),
  actor_email  text NOT NULL,
  actor_name   text NOT NULL,
  action       text NOT NULL CHECK (action IN ('approve','reject')),
  comment      text,
  source       text NOT NULL DEFAULT 'web' CHECK (source IN ('web','telegram','email')),
  acted_at     text NOT NULL DEFAULT iso_now()
);
CREATE INDEX idx_approvals_proposal ON approvals(proposal_id, acted_at);

-- 9. notifications
CREATE TABLE notifications (
  id                integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  proposal_id       integer NOT NULL REFERENCES proposals(id) ON DELETE CASCADE,
  channel           text NOT NULL CHECK (channel IN ('email','telegram')),
  event             text NOT NULL,
  recipient         text NOT NULL,
  status            text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','sent','failed')),
  provider_msg_id   text,
  error             text,
  attempts          integer NOT NULL DEFAULT 0,
  created_at        text NOT NULL DEFAULT iso_now(),
  sent_at           text
);
CREATE INDEX idx_notif_proposal ON notifications(proposal_id);
CREATE INDEX idx_notif_pending  ON notifications(status) WHERE status = 'pending';

-- 10. audit_log
CREATE TABLE audit_log (
  id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_type  text NOT NULL,
  entity_id    text NOT NULL,
  actor_email  text,
  action       text NOT NULL,
  old_value    text,
  new_value    text,
  ip_address   text,
  user_agent   text,
  created_at   text NOT NULL DEFAULT iso_now()
);
CREATE INDEX idx_audit_entity ON audit_log(entity_type, entity_id, created_at);

-- 11. engineering_members + ic_members [0005]
CREATE TABLE engineering_members (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_email    text NOT NULL UNIQUE,
  user_name     text NOT NULL,
  routing_order integer NOT NULL DEFAULT 1,
  is_active     integer NOT NULL DEFAULT 1,
  created_at    text NOT NULL DEFAULT iso_now()
);
CREATE TABLE ic_members (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_email    text NOT NULL UNIQUE,
  user_name     text NOT NULL,
  routing_order integer NOT NULL DEFAULT 1,
  is_active     integer NOT NULL DEFAULT 1,
  created_at    text NOT NULL DEFAULT iso_now()
);

-- 12. ephemeral_kv — thay Cloudflare KV (oidc state, tg pending, cache app-token)
CREATE TABLE ephemeral_kv (
  key        text PRIMARY KEY,
  value      text NOT NULL,
  expires_at text          -- ISO UTC; null = không hết hạn
);
CREATE INDEX idx_ephemeral_kv_expires ON ephemeral_kv(expires_at);
