-- Audit log BẤT BIẾN cho hành động phê duyệt (non-repudiation Tầng 1).
-- Ghi đầy đủ ngữ cảnh tại thời điểm user duyệt/từ chối: ai, lúc nào, từ IP/thiết bị nào,
-- qua kênh nào (web/telegram), phiên nào. Phục vụ tra log + chống chối "tôi không duyệt".
--
-- KHÔNG đặt FK tới proposals (và KHÔNG cascade): log phải tồn tại độc lập, kể cả khi
-- phiếu bị xoá (approvals đang ON DELETE CASCADE nên không dùng để lưu vết lâu dài được).

CREATE TABLE IF NOT EXISTS audit_events (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_time       text NOT NULL DEFAULT iso_now(),  -- ISO server time (UTC)
  event_type       text NOT NULL,                    -- 'approve' | 'reject' | ...
  actor_email      text NOT NULL,
  actor_name       text NOT NULL,
  actor_user_id    text,                             -- Entra GUID (web) / users.id
  proposal_id      integer,                          -- không FK (giữ vết khi phiếu bị xoá)
  step             text,                             -- manager/engineering/ic/bod
  action           text,                             -- approve/reject
  channel          text NOT NULL,                    -- web | telegram
  ip               text,                             -- CF-Connecting-IP (IP thật qua tunnel)
  user_agent       text,
  session_ref      text,                             -- hash 16 hex của cookie phiên (không lộ secret)
  telegram_chat_id text,
  detail           text                              -- JSON phụ (status mới, lý do, auto-skip…)
);

CREATE INDEX IF NOT EXISTS idx_audit_proposal ON audit_events (proposal_id);
CREATE INDEX IF NOT EXISTS idx_audit_actor    ON audit_events (actor_email);
CREATE INDEX IF NOT EXISTS idx_audit_time     ON audit_events (event_time);

-- Append-only: chặn UPDATE/DELETE để log không bị sửa khống. (Owner vẫn có thể tắt trigger —
-- chống tampering ở mức admin là việc của Tầng 3: hash-chain + anchor ra ngoài.)
CREATE OR REPLACE FUNCTION audit_events_no_mutate() RETURNS trigger AS $$
BEGIN
  RAISE EXCEPTION 'audit_events là append-only: không được % bản ghi (id=%)', TG_OP, OLD.id;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_audit_events_no_mutate ON audit_events;
CREATE TRIGGER trg_audit_events_no_mutate
  BEFORE UPDATE OR DELETE ON audit_events
  FOR EACH ROW EXECUTE FUNCTION audit_events_no_mutate();
