-- Phase 2: KSNB theo dõi mua hàng SAU khi phiếu mua hàng được duyệt (status='completed').
-- Giai đoạn mua sắm chạy SONG SONG, không đụng state máy duyệt. Không theo thứ tự cố định
-- (có đơn cần đặt cọc/thanh toán trước nhiều đợt) → dùng nhật ký hoạt động.

-- 1 dòng/phiếu: trạng thái mua sắm tổng + mốc hoàn tất.
CREATE TABLE IF NOT EXISTS procurement (
  proposal_id      integer PRIMARY KEY REFERENCES proposals(id) ON DELETE CASCADE,
  status           text NOT NULL DEFAULT 'pending',  -- pending | in_progress | done
  done_at          text,
  done_by_user_id  text,
  done_by_name     text,
  done_note        text,
  created_at       text NOT NULL DEFAULT iso_now(),
  updated_at       text NOT NULL DEFAULT iso_now()
);

-- Nhật ký hoạt động mua sắm (thêm bất kỳ lúc nào, bất kỳ thứ tự).
CREATE TABLE IF NOT EXISTS procurement_event (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  proposal_id        integer NOT NULL REFERENCES proposals(id) ON DELETE CASCADE,
  type               text NOT NULL,   -- order | receive | payment | other
  event_date         text,            -- ngày thực hiện (text, do user nhập)
  percent            numeric,         -- % thanh toán (chỉ dùng khi type='payment')
  note               text,
  created_by_user_id text,
  created_by_name    text,
  created_at         text NOT NULL DEFAULT iso_now()
);
CREATE INDEX IF NOT EXISTS idx_procurement_event_pid ON procurement_event (proposal_id);
