-- Phase 2: hồ sơ mua hàng đính kèm (KSNB upload).
-- Tách 2 tầng: metadata ở bảng này; file thật ở object layer (filesystem volume)
-- tại UPLOAD_DIR/<storage_key>, tên file = UUID (chống path traversal). sha256 để verify
-- toàn vẹn. Mỗi upload/xoá ghi audit_events (append-only) — lớp chống chối.
CREATE TABLE IF NOT EXISTS procurement_attachment (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  proposal_id         integer NOT NULL REFERENCES proposals(id) ON DELETE CASCADE,
  storage_key         text NOT NULL UNIQUE,   -- UUID file trên đĩa (KHÔNG phải path)
  filename            text NOT NULL,           -- tên gốc người upload (hiển thị/tải về)
  mime                text NOT NULL,
  size                bigint NOT NULL,
  sha256              text NOT NULL,
  uploaded_by_user_id text,
  uploaded_by_name    text,
  created_at          text NOT NULL DEFAULT iso_now()
);
CREATE INDEX IF NOT EXISTS idx_proc_attach_pid ON procurement_attachment (proposal_id);
