-- Phase 3: Theo dõi HÓA ĐƠN NCC + công nợ — thay sổ Excel "THEO DÕI CÔNG NỢ NCC".
-- Luồng: mail HĐĐT (nhiều nhà cung cấp: easyinvoice/VNPT/Viettel/MISA...) về shared mailbox
--   → cron ingest đọc → parse (HTML/link hoặc XML đính kèm TT78) → tạo dòng status='pending'
--   → người dùng xác nhận (nhà máy / NCC / gắn phiếu) → 'confirmed'. Máy đọc, người duyệt (KSNB).

-- Danh mục NHÀ MÁY (seed từ Excel) — dùng cho dropdown chọn chi nhánh.
CREATE TABLE IF NOT EXISTS branch (
  name       text PRIMARY KEY,
  sort_order integer NOT NULL DEFAULT 0,
  active     integer NOT NULL DEFAULT 1
);

-- Map MST bên MUA (pháp nhân trên HĐ) → NHÀ MÁY. Admin cấu hình trên web.
-- Quy tắc đã chốt: nhà máy xác định theo pháp nhân người mua trên hóa đơn.
CREATE TABLE IF NOT EXISTS buyer_branch_map (
  buyer_tax_code text PRIMARY KEY,
  buyer_name     text,
  branch         text NOT NULL REFERENCES branch(name),
  created_at     text NOT NULL DEFAULT iso_now(),
  updated_at     text NOT NULL DEFAULT iso_now()
);

-- Alias MST bên BÁN → tên ngắn NCC (sổ Excel dùng tên ngắn, vd "NGÂN LỘC PHÚ").
-- Tự tạo (short_name = tên đầy đủ) lần đầu gặp; admin sửa lại tên ngắn sau.
CREATE TABLE IF NOT EXISTS supplier_alias (
  seller_tax_code text PRIMARY KEY,
  seller_name     text,
  short_name      text NOT NULL,
  created_at      text NOT NULL DEFAULT iso_now(),
  updated_at      text NOT NULL DEFAULT iso_now()
);

-- Header hóa đơn NCC.
CREATE TABLE IF NOT EXISTS supplier_invoice (
  id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- nguồn
  source               text NOT NULL DEFAULT 'email',  -- email | manual
  source_message_id    text,                           -- Graph message id (dedup mail)
  provider             text,                           -- easyinvoice | vnpt | viettel | misa | xml...
  invoice_url          text,
  -- định danh HĐ
  serial               text,            -- ký hiệu (1C26THT)
  invoice_no           text,            -- số (632)
  invoice_date         text,            -- ngày HĐ (YYYY-MM-DD)
  tax_auth_code        text,            -- mã cơ quan thuế
  lookup_code          text,            -- mã tra cứu
  -- bên bán
  seller_tax_code      text,
  seller_name          text,
  seller_address       text,
  -- bên mua
  buyer_tax_code       text,
  buyer_name           text,
  buyer_address        text,
  -- tiền (đơn vị: VND, số nguyên/thập phân)
  currency             text DEFAULT 'VND',
  exchange_rate        numeric,
  subtotal             numeric,         -- cộng tiền hàng (trước thuế)
  vat_rate             numeric,         -- phân số: 0.08 = 8%
  vat_amount           numeric,
  total                numeric,         -- tổng thanh toán (gồm thuế)
  amount_words         text,
  -- phân loại + KSNB
  branch               text,            -- NHÀ MÁY (auto từ buyer_tax_code, sửa được)
  supplier_short       text,            -- tên ngắn NCC (auto từ supplier_alias)
  proposal_id          integer REFERENCES proposals(id) ON DELETE SET NULL,
  proposal_code        text,            -- PHIẾU ĐỀ XUẤT (text tự do nếu chưa có trong hệ thống)
  -- thanh toán / công nợ
  payment_status       text NOT NULL DEFAULT 'unpaid',  -- unpaid | partial | paid
  paid_amount          numeric NOT NULL DEFAULT 0,
  doc_submit_date      text,            -- ngày nộp chứng từ
  receive_date         text,            -- ngày nhận hàng
  note                 text,
  -- vòng đời bản ghi
  status               text NOT NULL DEFAULT 'pending', -- pending | confirmed | rejected
  confirmed_at         text,
  confirmed_by_user_id text,
  confirmed_by_name    text,
  created_at           text NOT NULL DEFAULT iso_now(),
  updated_at           text NOT NULL DEFAULT iso_now(),
  -- dedup HĐ trùng (cùng bên bán + ký hiệu + số). NULL coi như distinct (Postgres mặc định).
  UNIQUE (seller_tax_code, serial, invoice_no)
);
CREATE INDEX IF NOT EXISTS idx_supplier_invoice_status ON supplier_invoice (status);
CREATE INDEX IF NOT EXISTS idx_supplier_invoice_branch ON supplier_invoice (branch);
CREATE INDEX IF NOT EXISTS idx_supplier_invoice_buyer  ON supplier_invoice (buyer_tax_code);
CREATE INDEX IF NOT EXISTS idx_supplier_invoice_msg    ON supplier_invoice (source_message_id);

-- Dòng chi tiết vật tư/dịch vụ.
CREATE TABLE IF NOT EXISTS supplier_invoice_line (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_id  bigint NOT NULL REFERENCES supplier_invoice(id) ON DELETE CASCADE,
  seq         integer NOT NULL,   -- STT
  item_name   text,
  unit        text,               -- ĐVT
  qty         numeric,
  unit_price  numeric,
  vat_rate    numeric,
  amount      numeric             -- thành tiền trước thuế (= qty * unit_price)
);
CREATE INDEX IF NOT EXISTS idx_supplier_invoice_line_inv ON supplier_invoice_line (invoice_id);

-- Đánh dấu mail đã xử lý (kể cả mail không phải hóa đơn) để cron không quét lại.
CREATE TABLE IF NOT EXISTS invoice_mail_seen (
  message_id  text PRIMARY KEY,
  received_at text,
  outcome     text,               -- parsed | no_invoice | error
  detail      text,
  created_at  text NOT NULL DEFAULT iso_now()
);

-- Seed danh mục nhà máy (rút từ sổ Excel hiện hành).
INSERT INTO branch (name, sort_order) VALUES
  ('SINH KHỐI', 1),
  ('HỐ NAI', 2),
  ('DUY KHƯƠNG', 3),
  ('THUẬN GIAO', 4),
  ('KONTUM', 5),
  ('HÀ TĨNH', 6),
  ('PHÚ THỌ', 7),
  ('AVPE', 8),
  ('TÂY SƠN', 9)
ON CONFLICT (name) DO NOTHING;
