-- Đợt 1 — GIẤY ĐỀ NGHỊ THANH TOÁN (DNTT), mẫu AVPG-AC-P1-F1.
-- Giai đoạn này CHƯA có duyệt điện tử: người dùng tạo phiếu từ template → in ra giấy
-- → đi trình ký TAY. Hệ thống chỉ bám vết hồ sơ giấy đang nằm ở chặng nào.
-- Chuỗi chặng cố định (current_stage 0..5):
--   0 Nhập → 1 Trưởng bộ phận ký → 2 KSNB ký → 3 Kế toán ký → 4 BOD ký → 5 Đã thanh toán

-- Bộ đếm mã DNTT riêng (tách khỏi proposal_counters để số phiếu không lẫn với Đề Xuất).
CREATE TABLE IF NOT EXISTS payment_counters (
  dept_code text NOT NULL,
  date_key  text NOT NULL,            -- DDMMYYYY giờ VN
  counter   integer NOT NULL DEFAULT 0,
  PRIMARY KEY (dept_code, date_key)
);

-- Header phiếu DNTT.
CREATE TABLE IF NOT EXISTS payment_request (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code              text UNIQUE,                       -- {DEPT}{NN}-{DDMMYYYY}, sinh khi tạo
  status            text NOT NULL DEFAULT 'draft',     -- draft | in_progress | paid | cancelled
  current_stage     integer NOT NULL DEFAULT 0,        -- 0..5 (xem chú thích trên)
  -- người tạo (snapshot từ phiên đăng nhập)
  creator_user_id   text,
  creator_email     text NOT NULL,
  creator_name      text,
  dept_code         text NOT NULL,
  -- header trên phiếu
  payee_name        text,           -- Họ & tên người thanh toán
  payee_title       text,           -- Chức danh
  purpose           text,           -- Mục đích thanh toán
  -- tổng & hình thức thanh toán
  total_amount      numeric NOT NULL DEFAULT 0,
  amount_words      text,           -- Bằng chữ (auto từ total, sửa được)
  pay_form          text,           -- Hình thức thanh toán (vd: Công ty / Cá nhân ứng trước)
  receive_form      text,           -- Hình thức nhận tiền: CK | TM
  bank_account_name text,           -- Tên chủ tài khoản
  bank_account_no   text,           -- Số tài khoản người nhận
  bank_name         text,           -- Ngân hàng (tuỳ chọn)
  transfer_note     text,           -- Nội dung CK
  note              text,           -- Ghi chú chung
  created_at        text NOT NULL DEFAULT iso_now(),
  updated_at        text NOT NULL DEFAULT iso_now()
);
CREATE INDEX IF NOT EXISTS idx_payment_request_creator ON payment_request (creator_email);
CREATE INDEX IF NOT EXISTS idx_payment_request_status ON payment_request (status);

-- Bảng kê chi tiết (Diễn giải | Đơn giá | SL | Số tiền | Loại tiền | Ghi chú).
CREATE TABLE IF NOT EXISTS payment_request_item (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pr_id       bigint NOT NULL REFERENCES payment_request(id) ON DELETE CASCADE,
  seq         integer NOT NULL,
  description text,            -- Diễn giải
  unit_price  numeric,         -- Đơn giá
  qty         numeric,         -- SL
  amount      numeric,         -- Số tiền
  currency    text DEFAULT 'VND', -- Loại tiền
  note        text             -- Ghi chú
);
CREATE INDEX IF NOT EXISTS idx_payment_request_item_pr ON payment_request_item (pr_id);

-- Lịch sử trình ký (append-only) — bám vết hồ sơ giấy: mỗi lần chuyển/lùi chặng hoặc
-- ghi chú vị trí đều thêm 1 dòng, không sửa/xoá.
CREATE TABLE IF NOT EXISTS payment_request_stage_log (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pr_id       bigint NOT NULL REFERENCES payment_request(id) ON DELETE CASCADE,
  stage_index integer NOT NULL,   -- chặng phiếu chuyển TỚI (hoặc chặng được ghi chú)
  stage_name  text NOT NULL,
  kind        text NOT NULL DEFAULT 'advance', -- advance | revert | note | cancel | create
  actor_email text NOT NULL,
  actor_name  text,
  note        text,               -- ai đang giữ hồ sơ / tình trạng / lý do
  acted_at    text NOT NULL DEFAULT iso_now()
);
CREATE INDEX IF NOT EXISTS idx_pr_stage_log_pr ON payment_request_stage_log (pr_id);
