-- DNTT ký điện tử qua Documenso (self-host). Bổ sung liên kết envelope + bản PDF đã ký.
-- Luồng: phiếu draft → "Gửi ký điện tử" tạo document bên Documenso (4 người ký) →
-- webhook Documenso đẩy current_stage tự động → completed thì kéo PDF ký về FILES.
-- Xem docs/documenso-dntt-integration.md.

ALTER TABLE payment_request ADD COLUMN IF NOT EXISTS documenso_document_id integer; -- id document (số) bên Documenso
ALTER TABLE payment_request ADD COLUMN IF NOT EXISTS documenso_envelope_id text;    -- envelopeId (chuỗi) bên Documenso
ALTER TABLE payment_request ADD COLUMN IF NOT EXISTS documenso_status text;         -- DRAFT|PENDING|COMPLETED|REJECTED|CANCELLED (mirror)
ALTER TABLE payment_request ADD COLUMN IF NOT EXISTS signed_pdf_key text;           -- storage key (FILES) bản PDF đã ký
ALTER TABLE payment_request ADD COLUMN IF NOT EXISTS signed_pdf_sha256 text;        -- hash bản ký (anchor chống tamper)
ALTER TABLE payment_request ADD COLUMN IF NOT EXISTS sign_sent_at text;             -- thời điểm gửi ký
ALTER TABLE payment_request ADD COLUMN IF NOT EXISTS signed_completed_at text;      -- thời điểm hoàn tất ký

CREATE INDEX IF NOT EXISTS idx_payment_request_docso ON payment_request (documenso_document_id);

-- Map recipient Documenso → chặng/vai trò để webhook biết ai ký ứng với stage nào.
CREATE TABLE IF NOT EXISTS payment_request_signer (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pr_id         bigint NOT NULL REFERENCES payment_request(id) ON DELETE CASCADE,
  role          text NOT NULL,          -- manager | ksnb | acct | bod
  stage_index   integer NOT NULL,       -- chặng tương ứng (1 | 2/3 | 4) — gán động theo mid_order khi ký
  recipient_id  bigint,                 -- id recipient bên Documenso
  email         text NOT NULL,
  name          text,
  signed_at     text
);
CREATE INDEX IF NOT EXISTS idx_pr_signer_pr ON payment_request_signer (pr_id);
CREATE INDEX IF NOT EXISTS idx_pr_signer_recipient ON payment_request_signer (recipient_id);
