-- Thông báo in-app (chuông header) — khác bảng `notifications` (hàng đợi gửi email/telegram).
-- Hiện dùng cho DNTT: mỗi khi có người ký điện tử qua Documenso, đẩy 1 thông báo cho
-- NGƯỜI TẠO phiếu để họ biết tiến độ ký (webhook integrations-documenso.ts gọi enqueueInbox).
-- Generic theo `recipient` (email) nên module khác tái dùng được sau này.

CREATE TABLE IF NOT EXISTS inbox_notification (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recipient     text NOT NULL,          -- email người nhận (lowercase)
  kind          text NOT NULL,          -- 'pr_signed' | 'pr_completed' | ...
  title         text NOT NULL,          -- tiêu đề ngắn hiện trên toast/chuông
  body          text,                   -- chi tiết (tuỳ chọn)
  link          text,                   -- đường dẫn mở khi bấm (vd '/payments/123')
  pr_id         bigint,                 -- tham chiếu phiếu (tuỳ chọn, để truy vết)
  read_at       text,                   -- NULL = chưa đọc
  created_at    text NOT NULL DEFAULT iso_now()
);

-- Truy vấn chính: đếm/đọc thông báo của 1 người, mới nhất trước.
CREATE INDEX IF NOT EXISTS idx_inbox_recipient ON inbox_notification (recipient, id DESC);
CREATE INDEX IF NOT EXISTS idx_inbox_unread ON inbox_notification (recipient, read_at);
