-- Đợt 1 (bổ sung) — SỔ TÀI KHOẢN THỤ HƯỞNG dùng chung cho Giấy Đề Nghị Thanh Toán.
-- Mục tiêu: thông tin chuyển khoản (chủ TK + số TK + ngân hàng) nhập 1 lần được lưu lại,
-- lần sau chọn nhanh từ dropdown thay vì gõ lại. Phạm vi: dùng chung toàn công ty
-- (một NCC/đối tác có thể nhận tiền từ nhiều người tạo phiếu).
--
-- Khoá trùng theo (số TK + ngân hàng) đã chuẩn hoá: cùng số TK + cùng ngân hàng = một bản ghi,
-- nhập lại chỉ tăng use_count để gợi ý các tài khoản hay dùng lên đầu. bank_name lưu '' (rỗng)
-- thay vì NULL để ON CONFLICT (account_no, bank_name) hoạt động sạch sẽ.
CREATE TABLE IF NOT EXISTS payment_beneficiary (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_name  text NOT NULL,                 -- Tên chủ tài khoản
  account_no    text NOT NULL,                 -- Số tài khoản
  bank_name     text NOT NULL DEFAULT '',      -- Ngân hàng (tên ngắn, '' nếu chưa rõ)
  use_count     integer NOT NULL DEFAULT 1,    -- số lần dùng → sắp xếp gợi ý
  created_by    text,                          -- email người nhập đầu tiên
  created_at    text NOT NULL DEFAULT iso_now(),
  last_used_at  text NOT NULL DEFAULT iso_now()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_payment_beneficiary_acct
  ON payment_beneficiary (account_no, bank_name);
