-- Đợt 2 DNTT (thay chức năng "Đề nghị thanh toán" của WorkIT): bổ sung tính năng lấy từ WorkIT.
-- Feature 2 (NCC/đối tượng nhận tiền: địa chỉ + MST), 3 (danh mục công ty chi tiền),
-- 4 (ngày cần thanh toán), 5 (đính kèm hồ sơ), 12 (bình luận trao đổi).
-- Feature 6 (từ chối/sao chép) + 11 (lọc/xuất Excel/dashboard) là thuần route, không cần schema.

-- ── Feature 4: Ngày cần thanh toán (due date) ──
ALTER TABLE payment_request ADD COLUMN IF NOT EXISTS due_date text;   -- ISO yyyy-mm-dd, NULL nếu không đặt

-- ── Feature 2: đối tượng nhận tiền (NCC/KH) — địa chỉ + MST, autofill khi chọn TK đã lưu ──
ALTER TABLE payment_request     ADD COLUMN IF NOT EXISTS beneficiary_address  text;
ALTER TABLE payment_request     ADD COLUMN IF NOT EXISTS beneficiary_tax_code text;
ALTER TABLE payment_beneficiary ADD COLUMN IF NOT EXISTS address  text NOT NULL DEFAULT '';
ALTER TABLE payment_beneficiary ADD COLUMN IF NOT EXISTS tax_code text NOT NULL DEFAULT '';

-- ── Feature 3: danh mục CÔNG TY chi tiền — thay ô "Đi từ công ty" tự do bằng chọn từ danh mục ──
-- Seed các pháp nhân AVP Group (sửa/thêm được qua active + sort_order). name = hiển thị & lưu.
CREATE TABLE IF NOT EXISTS payment_company (
  name       text PRIMARY KEY,
  sort_order integer NOT NULL DEFAULT 0,
  active     integer NOT NULL DEFAULT 1
);
INSERT INTO payment_company (name, sort_order) VALUES
  ('An Việt Phát Group', 1),
  ('AVP Paper', 2),
  ('AVP Timber', 3),
  ('An Việt Năng Lượng', 4)
ON CONFLICT (name) DO NOTHING;

-- ── Feature 5: đính kèm hồ sơ vào DNTT (báo giá / hợp đồng / hoá đơn scan) ──
-- Tách 2 tầng như procurement_attachment: metadata ở đây, file thật ở FILES (UPLOAD_DIR/<key>).
CREATE TABLE IF NOT EXISTS payment_request_attachment (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pr_id               bigint NOT NULL REFERENCES payment_request(id) ON DELETE CASCADE,
  storage_key         text NOT NULL UNIQUE,   -- UUID file trên đĩa (KHÔNG phải path)
  filename            text NOT NULL,           -- tên gốc hiển thị/tải về
  mime                text NOT NULL,
  size                bigint NOT NULL,
  sha256              text NOT NULL,           -- verify toàn vẹn
  uploaded_by_user_id text,
  uploaded_by_name    text,
  created_at          text NOT NULL DEFAULT iso_now()
);
CREATE INDEX IF NOT EXISTS idx_pr_attach_pid ON payment_request_attachment (pr_id);

-- ── Feature 12: bình luận trao đổi trên phiếu (khác stage_log — luồng thảo luận tự do) ──
CREATE TABLE IF NOT EXISTS payment_request_comment (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pr_id        bigint NOT NULL REFERENCES payment_request(id) ON DELETE CASCADE,
  author_email text NOT NULL,
  author_name  text,
  body         text NOT NULL,
  created_at   text NOT NULL DEFAULT iso_now()
);
CREATE INDEX IF NOT EXISTS idx_pr_comment_pid ON payment_request_comment (pr_id);
